const { error } = require("console");
const fs = require("fs");

const syncContent = "this content generated by Sync writeFile method";
const asyncContent = "this content generated by Async writeFile method";

// sync... - write file
fs.writeFileSync("./sync_new_file.txt", syncContent);

// async... - write file
fs.writeFile("./async_new_file.txt", asyncContent, (err) => {});

console.log("\n\n");

// sync... - read file
const syncRead = fs.readFileSync("./contacts.txt", "utf-8");
console.log("syncRead => ", syncRead);

console.log("\n");

// async... - read file
fs.readFile("./contacts.txt", "utf-8", (err, result) => {
  err ? console.log("Error => ", err) : console.log("asyncRead => ", result);
});

let date = new Date();
// sync... - append file
fs.appendFileSync(
  "./logs.txt",
  `${date.getHours().toString()}:${date.getMinutes().toString()}:${date
    .getSeconds()
    .toString()} - Logged In [sync call] \n`
);

// async... - read file
fs.appendFile(
  "./logs.txt",
  `${date.getHours().toString()}:${date.getMinutes().toString()}:${date
    .getSeconds()
    .toString()} - Logged In [async call] \n`,
  (err) => {}
);

// NOTE: There so many functions which will not be fully covered in this tutorial you can checkout the libraray of "fs" for more learnings
